name: release

on:
  push:
    branches:
      - develop

jobs:
  qa-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Check if version has been updated
      id: version_check
      uses: EndBug/version-check@v1
      with:
        diff-search: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Android APK
      if: steps.version_check.outputs.changed == 'true'
      run: |
        npm install -g @angular/cli
        npm install -g @ionic/cli
        npm install
        ionic build
        npx cap sync
        cd android/
        ./gradlew assembleDebug
        cd ..

    - name: Create GitHub release
      id: create_release
      if: steps.version_check.outputs.changed == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_check.outputs.version }}
        release_name: ${{ steps.version_check.outputs.version }}
        body: |
          ![release!](https://i.giphy.com/media/lPulaaB9lDMnGZiivs/source.gif)
          
          # Changelog

          Release type: ${{ steps.version_check.outputs.type }}
        prerelease: true

    - name: Upload APKs to release assets
      if: steps.version_check.outputs.changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/app/build/outputs/apk/debug/app-debug.apk
        asset_name: app-debug.apk
        asset_content_type: application/vnd.android.package-archive